import { BATTLE_STUDENTS, battleStudentById } from './battleCast.js'
import { publicAssetUrl } from './publicAssetUrl.js'

const revealChoice = (id, emoji, label, response, emotionId) => ({
  id,
  emoji,
  label,
  response,
  emotionId,
})

function revealScene({
  studentId,
  title,
  place,
  image,
  imageAlt,
  discovery,
  caughtLine,
  acceptLabel,
  acceptResponse,
  joinLabel,
  joinResponse,
  secretLabel,
  secretResponse,
  growth = null,
}) {
  return {
    studentId,
    title,
    place,
    image,
    imageAlt,
    discovery,
    caughtLine,
    choices: [
      revealChoice('accept', '✨', acceptLabel, acceptResponse, 'relieved'),
      revealChoice('join', '🤝', joinLabel, joinResponse, 'delighted'),
      revealChoice('secret', '🤫', secretLabel, secretResponse, 'embarrassed'),
    ],
    growth,
  }
}

export const CHARACTER_REVEAL_SCENES = {
  mio: revealScene({
    studentId: 'mio',
    title: '三皿目で目が合った',
    place: '放課後の喫茶店',
    image: publicAssetUrl('/assets/battle/reveals/mio.webp'),
    imageAlt: '大きめのパフェと二枚の空皿を前に、見つかって照れるミオ',
    discovery: 'あなたが喫茶店へ入ると、奥の席にミオがいた。普通サイズの大きめパフェと、すでに空になった二枚の皿。三口目ではなく、三皿目で目が合った。',
    caughtLine: '「……いつから見てたの？　これは今日だけじゃなくて、その……いつも、これくらいです」',
    acceptLabel: '「気持ちいい食べっぷり」',
    acceptResponse: '笑わないんだ。よかった。甘いものを食べるときだけは、遠慮より幸せを優先したいの。',
    joinLabel: '「次は一緒に食べよう」',
    joinResponse: '本当？　じゃあ二人で別の味を頼んで、途中で交換しよう。候補はもう四つあるよ。',
    secretLabel: '「みんなには内緒？」',
    secretResponse: '少しだけ内緒にして。今度みんなで来たとき、平然と三皿目を頼んで驚かせたいから。',
  }),
  ren: revealScene({
    studentId: 'ren',
    title: '猫語が聞こえた路地',
    place: '公園わきの細い道',
    image: publicAssetUrl('/assets/battle/reveals/ren.webp'),
    imageAlt: '三匹の猫に囲まれて、見つかって振り返るレン',
    discovery: '公園の裏から聞いたことのない甘い声がして、あなたは路地をのぞいた。三匹の猫へ話しかけていたレンが振り返り、開いたスケッチ帳を慌てて押さえる。',
    caughtLine: '「今の声は忘れて。こいつらには、このくらいで話す方が通じるんだ」',
    acceptLabel: '「猫にはその声なんだ」',
    acceptResponse: '言い方に悪意がないのが余計に恥ずかしい。でも、この子たちが安心するなら仕方ないだろ。',
    joinLabel: '「私にも紹介して」',
    joinResponse: 'いいよ。黒い子がスミ、真ん中がモチ、茶色い子がチャイ。近づく順番も教える。',
    secretLabel: '「絵も見なかったことに？」',
    secretResponse: 'それは……完成したら見せる。今は猫の顔より、僕の顔の方が赤く描けそうだから。',
  }),
  haru: revealScene({
    studentId: 'haru',
    title: '図書室より大きな声',
    place: '実家のうどん店',
    image: publicAssetUrl('/assets/battle/reveals/haru.webp'),
    imageAlt: '前掛けと手ぬぐい姿で、きつねうどんを運ぶハル',
    discovery: '昼どき、あなたが初めて入ったうどん店で「いらっしゃい！」とよく通る声がした。前掛け姿で、きつねうどんを運んできたのはハルだった。',
    caughtLine: '「いらっしゃい！　……って、君！？　学校では小声なのに、って顔をしてるね」',
    acceptLabel: '「看板店員、似合ってる」',
    acceptResponse: 'ありがとう。家では本を探す人より、空いた席を探す人の方が多いからね。声も自然に大きくなるんだ。',
    joinLabel: '「おすすめをお願い」',
    joinResponse: 'それなら、だしを変えた今日のきつねうどん。感想は短くてもいいから、あとで聞かせて。',
    secretLabel: '「学校では黙っておく？」',
    secretResponse: '店のことは隠さなくていいよ。ただ、「いらっしゃい！」を図書室で再現するのだけはやめてほしい。',
  }),
  akari: revealScene({
    studentId: 'akari',
    title: '実験より夢中',
    place: '夕方の近所の公園',
    image: publicAssetUrl('/assets/battle/reveals/akari.webp'),
    imageAlt: '犬用のおもちゃを持って、犬と遊ぶところを見つかったアカリ',
    discovery: '公園を通りかかったあなたの前を、ボールと犬が勢いよく横切った。「もう一回！」と誰より楽しそうに追いかけていたアカリが、ようやくこちらへ気づく。',
    caughtLine: '「観測者がいた！　今の声の高さは、その……犬にだけ反応する特殊条件だから！」',
    acceptLabel: '「実験中より楽しそう」',
    acceptResponse: 'ばれた？　この子は予想外の動きばかりで、どんな実験より観察しがいがあるんだ。',
    joinLabel: '「次の一投、やらせて」',
    joinResponse: 'もちろん！　安全距離は確認済み。投げる角度だけ変えて、どこが一番喜ぶか試そう。',
    secretLabel: '「高い声も記録する？」',
    secretResponse: 'それは記録対象外！　でも、誰にも言わないなら犬用おもちゃの設計図は見せてあげる。',
  }),
  kaito: revealScene({
    studentId: 'kaito',
    title: '最速のお兄ちゃん',
    place: '休日の公園入口',
    image: publicAssetUrl('/assets/battle/reveals/kaito.webp'),
    imageAlt: '妹の靴ひもを結び、うさぎのリュックも持つカイト',
    discovery: '休日の公園で、あなたは地面へ片膝をつくカイトを見つけた。妹のヒナの靴ひもを結び直し、うさぎのリュックも水筒も自分で持っている。',
    caughtLine: '「あ、こいつ妹のヒナ。靴ひもくらい普通だろ。……別に、過保護じゃないからな？」',
    acceptLabel: '「すごくいいお兄ちゃんだね」',
    acceptResponse: '本人の前で言うなって、調子に乗るから。でもまあ、転ばず帰れたら今日は俺の勝ち。',
    joinLabel: '「三人で遊ぼう」',
    joinResponse: 'いいな！　ヒナ、鬼ごっこはどうする？　……俺が鬼？　最初から本気で逃げろよ。',
    secretLabel: '「学校では内緒？」',
    secretResponse: '隠すことじゃないけど、「うさぎリュックが似合う」は絶対に広めるなよ。そこだけ約束。',
  }),
  rei: revealScene({
    studentId: 'rei',
    title: '待ち合わせを二度通り過ぎた',
    place: '休日のショッピングアーケード',
    image: publicAssetUrl('/assets/battle/reveals/rei.webp'),
    imageAlt: '華やかな休日メイクと私服で、手を振るレイ',
    discovery: '待ち合わせ場所を二周してもレイがいない。三周目、華やかな服の人があなたへ手を振った。眼鏡を外し、ばっちりメイクをしたレイだと気づくまで数秒かかった。',
    caughtLine: '「三回目でようやく気づいたわね。学校の眼鏡がないと、そんなに別人？」',
    acceptLabel: '「本当にレイなんだ」',
    acceptResponse: '本人確認は完了ね。休日まで生徒会の顔をする必要はないでしょう？　今日はこっちの私よ。',
    joinLabel: '「その店、一緒に見たい」',
    joinResponse: 'いい判断ね。あなたに似合いそうな色も、通り過ぎる間に三つ見つけておいたわ。',
    secretLabel: '「学校では秘密にする？」',
    secretResponse: '秘密にする必要はないけれど、証拠写真なしで説明しても誰も信じないかもしれないわね。',
  }),
  nao: revealScene({
    studentId: 'nao',
    title: '千ピース分の沈黙',
    place: '国際交流部の部室',
    image: publicAssetUrl('/assets/battle/reveals/nao.webp'),
    imageAlt: '大きなジグソーパズルへ集中し、見つかって顔を上げるナオ',
    discovery: 'いつも話し声の絶えない部室が静かで、あなたはそっと扉を開けた。ナオは千ピースの風景へ黙々と向かい、最後の一枚を手にしたまま固まる。',
    caughtLine: '「いつからいたの！？　今ちょうど残り一枚で、世界から会話が消えてた……」',
    acceptLabel: '「静かなナオも新鮮」',
    acceptResponse: '自分でもびっくり。人と話すのと同じくらい、形だけでつながる瞬間も好きみたい。',
    joinLabel: '「最後の一枚、一緒に」',
    joinResponse: 'そこは譲れない……と言いたいけど、二人で同時にはめよう。完成の乾杯も必要だね！',
    secretLabel: '「無言だったことは秘密？」',
    secretResponse: 'それは秘密で！　国際交流部で一時間しゃべらなかった記録が知られたら大事件だから。',
  }),
  tsubaki: revealScene({
    studentId: 'tsubaki',
    title: '磁器の頬に宿るまなざし',
    place: '祖母の古い人形工房',
    image: publicAssetUrl('/assets/battle/reveals/tsubaki.webp'),
    imageAlt: '花柄の前掛けで、巻き髪とレースドレスのフランス人形へ筆を入れるツバキ',
    discovery: '祖母の古い工房を訪ねたあなたは、花柄の前掛けをしたツバキを見つけた。竹刀を握る手で、青いガラスの瞳をしたフランス人形の磁器の頬へ細い筆を運んでいる。机には巻き髪のかつら、レースのドレス、ボンネット、小さな革靴と未完成の素体が整然と並んでいた。',
    caughtLine: '「見られたか。この子の頬とまなざしが決まるまでは、誰にも見せないつもりだったんだが」',
    acceptLabel: '「レースも表情もきれい」',
    acceptResponse: 'ありがとう。磁器の白さに負けない、安心できる顔を描きたかった。そう見えたなら筆を置けそうだ。',
    joinLabel: '「ドレスを一緒に選びたい」',
    joinResponse: 'では隣へ。生成りのレースか、薄紫のリボンかで迷っている。君がこの子に似合うと思う方を聞かせてくれ。',
    secretLabel: '「道場では内緒？」',
    secretResponse: 'フランス人形作りは隠さない。ただ、花柄の前掛けまで詳しく話す必要はないと思う。必要は、ないぞ。',
  }),
  noa: revealScene({
    studentId: 'noa',
    title: '圏外の星空',
    place: '夜明け前の丘',
    image: publicAssetUrl('/assets/battle/reveals/noa.webp'),
    imageAlt: '端末を置き、小さな望遠鏡で星を見るところを見つかったノア',
    discovery: '夜明け前、あなたが丘へ着くと、小さな望遠鏡の横にノアがいた。端末は鞄の中。紙の星図だけで空を追っていた彼女が、足音に振り返る。',
    caughtLine: '「接続は切ってあるよ。たまには検索結果じゃなく、自分の目で最初に見つけたいから」',
    acceptLabel: '「オフラインのノアだ」',
    acceptResponse: '珍しいでしょ。でも空は読み込み待ちも更新通知もない。見逃したら、それも観測記録になる。',
    joinLabel: '「私にも見せて」',
    joinResponse: 'もちろん。接眼レンズをのぞいて、右上の明るい星からゆっくり左へ追ってみて。',
    secretLabel: '「この場所は秘密？」',
    secretResponse: '場所は秘密じゃない。でも静かに見られる人だけに教えたい。君ならアクセスを許可します。',
  }),
  yuu: revealScene({
    studentId: 'yuu',
    title: '一人だけのアンコール',
    place: '放課後のカラオケ店',
    image: publicAssetUrl('/assets/battle/reveals/yuu.webp'),
    imageAlt: '眼鏡と大きなパーカー姿でヒトカラ中、扉を開けられて驚くユウ',
    discovery: '部屋を間違えて扉を開けたあなたの耳へ、聞き覚えのない力強い歌声が飛び込んだ。眼鏡と大きなパーカー姿でヒトカラに没頭していたユウが、マイクを握ったまま固まる。',
    caughtLine: '「いつから聞いてたの……？　一人なら失敗しても誰にも嫌われないから、ここでは歌えるんだ」',
    acceptLabel: '「歌、本当に好きなんだね」',
    acceptResponse: 'うん。好きだからこそ、誰かの前で声が震えるのが怖かった。笑わず聞いてくれて、少しだけ助かった。',
    joinLabel: '「今度は一緒に歌おう」',
    joinResponse: 'いきなり大勢は無理だけど、君となら二人から始められるかも。次は扉を閉めずに待っているよ。',
    secretLabel: '「今日は二人だけの秘密」',
    secretResponse: 'ありがとう。でも、いつか自分から話せる秘密にしたい。まずは君の前で最後まで歌ってみる。',
    growth: {
      title: 'ひとりの歌が、みんなの前へ',
      intro: 'あの日、主人公が笑わず歌を受け止めたことから、ユウは急がず一歩ずつ人のいる場所へ進み始める。',
      steps: [
        {
          id: 'first-livehouse',
          eyebrow: 'FIRST STEP',
          title: '友達と初めてのライブハウスへ',
          image: publicAssetUrl('/assets/battle/reveals/yuu-livehouse.webp'),
          imageAlt: '友達と初めてライブハウスへ行き、客席でおそるおそる手を上げるユウ',
          text: '数週間後。主人公たちと初めてライブハウスへ行ったユウは、端の席から始め、最後の曲ではみんなと同じように手を上げた。その経験を足がかりに、やがて人前でも一曲を歌い切れるようになった。',
        },
      ],
    },
  }),
}

const FALLBACK_STUDENT_ID = BATTLE_STUDENTS[0].id

export function characterRevealSceneById(studentId) {
  const student = battleStudentById(studentId)
  return CHARACTER_REVEAL_SCENES[student.id]
    ?? CHARACTER_REVEAL_SCENES[FALLBACK_STUDENT_ID]
}
